### ISSUE TITLE
Feature request: point to NL/EN page on rijksmuseum.nl depending on lang of randomrijks.com

### ISSUE THREAD

**Issue by RaoOfPhysics** [StefanVDWeide/randomrijks-backend#1]
Hi @StefanVDWeide. Thanks for this nice app! I enjoyed poking around it for a few minutes earlier, after seeing your post on HN.

I wanted to know if it would be possible for the "More Information" box on a given object to point to the EN version of the collection page – e.g. https://www.rijksmuseum.nl/en/collection/RP-P-1968-172 – instead of the NL version – i.e. https://www.rijksmuseum.nl/nl/collectie/RP-P-1968-172 – if the user is in fact browsing the EN version of https://randomrijks.com/.

I believe the URL that "More Information" points to needs the following change when browsing the EN version of your website:

```diff
- /nl/collectie/
+ /en/collection/
```

Unfortunately, I’m not much of a programmer or I would’ve made a PR to address it, myself.

Thanks, once again, for building this. :)

**Comment by StefanVDWeide** [comment]
Hi @RaoOfPhysics,

Thanks for you for the kind words! I'm very happy to hear you enjoy the app and more importantly the art!

This is a good feature and something I've wanted to implement for a while. I've gone ahead and changed the behavior such that the selected language on the front-end will determines what version of the Rijks Museum website will open when clicking the `more information` button. 

Thanks again!

**Comment by RaoOfPhysics** [comment]
Just tested it and it works like a charm. :) I see that it was handled by some API wizardry. Thank you for the quick fix!
